- name: webhook workflows tpc demo
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook:
        host: 0.0.0.0
        port: 6969
        token: "{{ var_eda_token }}"
  rules:
    - name: Easytrade problem remediation
      condition: >-
        event.payload.eventData.application is match ("easytrade")
        and event.payload.eventData.action is match ("problem-remediation")
      actions:
        - print_event:
            pretty: true
        - run_job_template:
            name: Easytrade problem remediation
            organization: Default
    - name: Easytravel problem remediation
      condition: >-
        event.payload.eventData.application is match ("easytravel")
        and event.payload.eventData.action is match ("problem-remediation")
      actions:
        - print_event:
            pretty: true
        - run_job_template:
            name: Easytravel problem remediation
            organization: Default
