# - name: Listen for events on dt_webhook
#   hosts: all
#   sources:
#     - dynatrace.event_driven_ansible.dt_webhook:
#         host: 0.0.0.0
#         port: 6009
#         token: "{{ var_eda_token }}"
- name: webhook workflows tpc demo
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003
  rules:
    - name: generic print event
      condition: event.meta.headers is defined
      action:
        print_event:
          pretty: true
#     - name: Problem payload Dynatrace for App Failure rate increase issue
#       condition: event.payload.eventData.problemTitle is match ("Failure rate increase")
#       action:
#         run_job_template:
#           name: "AM-Remediate Failure rate"
#           organization: "Default"
#     - name: Problem payload Dynatrace for CPU issue
#       condition: event.payload.eventData.problemTitle is match ("CPU saturation")
#       action:
#         run_job_template:
#           name: "AM-Remediate CPU saturation"
#           organization: "Default"

